language: java
jdk: oraclejdk8

branches:
  only:
  - develop
  - master

services:
  - postgresql


before_script:
  - psql -c "CREATE DATABASE reverse_auction;" -U postgres
  - psql -c "CREATE USER db_user WITH PASSWORD 'reverseauction';" -U postgres

before_install:
  - chmod +x mvnw
script:
  - ./mvnw clean install -B

cache:
    directories:
    - $HOME/.m2
